# --- 通用路径 (可能会被命令行或主配置文件覆盖) ---
remote_work_dir: /data1/xiangkun/WORKSPACE/AtomThink_MCTS/zhoubokai/AtomThink/work_dir
output_dir: /data1/xiangkun/WORKSPACE/AtomThink_MCTS/zhoubokai/AtomThink/output_dir

### 测试数据
# 定义 MathVerse 数据集的位置和细节
# 数据集目录
dataset_dir: /data1/xiangkun/WORKSPACE/AtomThink_MCTS/zhoubokai/data/test_data # 建议使用绝对路径
dataset_name: MathVerse
# 图像目录
image_dir: /data1/xiangkun/WORKSPACE/AtomThink_MCTS/zhoubokai/data/test_data/MathVerse/images # 建议使用绝对路径
# 数据集文件名
dataset: MathVerse/testmini.json # 或者 test.json，取决于你想运行哪个
# prompt 模板 (应根据实际加载的模型调整)
template: llava # LLaVA 的默认模板
# 输入截断长度
cutoff_len: 4096 # model_max_length
