model_name_or_path: /data1/xiangkun/MODELS/Llama-3.2-Vision-11B
output_dir: evaluation_results/MathVerse_mcts
remote_work_dir: evaluation_results/MathVerse_mcts/remote_temp
answers_file: evaluation_results/MathVerse_mcts/inference/MathVerse/manual_run
trust_remote_code: true
use_fast_tokenizer: false
print_param_status: false
device_map: auto
prm_model: /data1/xiangkun/MODELS/Qwen2.5-Math-PRM-7B-local
prm_model_type: qwen_math_prm
prm_device_map: cuda:1
infer_dtype: float16
dataset_dir: data/test_data
dataset_name: MathVerse
image_dir: /data1/xiangkun/WORKSPACE/AtomThink_MCTS/zhoubokai/data/test_data/MathVerse/images
dataset: MathVerse/testmini.json
template: llava
cutoff_len: 4096
max_samples: 2
prompt: slow
method: mcts
temperature: 0.7
top_p: 0.9
top_k: 50
max_new_tokens: 4096
repetition_penalty: 1.0
candidate_num: 3
do_sample: true
mcts_iterations: 1000
mcts_exploration_const: 1.41
max_sampling_count: 300
max_single_step_sampling_count: 30
max_depth: 30
atomthink_beam_search_num: 2
image_resolution: 313600
max_memory:
  0: 23000MiB
  1: 6000MiB
