answers_file: evaluation_results/MathVerse_base/inference/MathVerse/0_6_0
cutoff_len: 4096
dataset: MathVerse/0_6_0.json
dataset_dir: data/test_data/parallel
dataset_name: MathVerse
device_map: auto
generating_args:
  atomthink_beam_search_num: 2
  candidate_num: 10
  do_sample: true
  max_new_tokens: 4096
  max_sampling_count: 300
  mcts_exploration_factor: 1.41
  mcts_iterations: 50
  method: base
  repetition_penalty: 1.0
  temperature: 0.0
  top_k: 50
  top_p: 0.7
image_dir: /data1/xiangkun/WORKSPACE/AtomThink_MCTS/zhoubokai/data/test_data/MathVerse/images
image_resolution: 313600
infer_dtype: float16
max_memory:
  0: 23000MiB
  1: 6000MiB
max_samples: null
method: base
model_name_or_path: /data1/xiangkun/MODELS/Llama-3.2-Vision-11B
output_dir: /data1/xiangkun/WORKSPACE/AtomThink_MCTS/zhoubokai/AtomThink/output_dir
print_param_status: false
prm_device_map: cuda:1
prompt: base
remote_answers_file: evaluation_results/MathVerse_base/remote_temp/inference/MathVerse/0_6_0
remote_work_dir: /data1/xiangkun/WORKSPACE/AtomThink_MCTS/zhoubokai/AtomThink/work_dir
separate_eval: true
template: llava
trust_remote_code: true
